
GET http://localhost:8080/src/asset_files/a.txt HTTP/1.1
x-pub-uiedbook-token: 65e0a3dbU2FsdGVkX18B85wvaBtH+0ju5OCq4oHgvHq5iiIcUtN9+ChjsqAUukeIeJaCi8Q/



###

GET http://localhost:8080/home HTTP/1.1
x-pub-uiedbook-token: 65e0a3dbU2FsdGVkX18B85wvaBtH+0ju5OCq4oHgvHq5iiIcUtN9+ChjsqAUukeIeJaCi8Q/



###

GET http://localhost:8080/post/home HTTP/1.1
x-pub-uiedbook-token: 65e0a3dbU2FsdGVkX18B85wvaBtH+0ju5OCq4oHgvHq5iiIcUtN9+ChjsqAUukeIeJaCi8Q/



###